import {
  Activity,
  BadgeCheck,
  Boxes,
  Bug,
  Building2,
  ClipboardCheck,
  Cloud,
  Compass,
  Cpu,
  Crosshair,
  Crown,
  Factory,
  FolderGit2,
  Gauge,
  Globe2,
  HeartPulse,
  Hexagon,
  KeyRound,
  Landmark,
  Layers,
  Lock,
  Map,
  MonitorSmartphone,
  Radar,
  RotateCcw,
  Scale,
  ScanSearch,
  Search,
  ShieldCheck,
  ShoppingBag,
  Siren,
  Sparkles,
  Swords,
  Terminal,
  Users,
  Workflow,
  Wrench,
  Code2,
} from "lucide-react";

const map = {
  badge: BadgeCheck,
  boxes: Boxes,
  bug: Bug,
  building: Building2,
  cart: ShoppingBag,
  clipboard: ClipboardCheck,
  cloud: Cloud,
  compass: Compass,
  cpu: Cpu,
  crosshair: Crosshair,
  crown: Crown,
  code: Code2,
  factory: Factory,
  gauge: Gauge,
  git: FolderGit2,
  globe: Globe2,
  heart: HeartPulse,
  hexagon: Hexagon,
  key: KeyRound,
  landmark: Landmark,
  layers: Layers,
  lock: Lock,
  map: Map,
  monitor: MonitorSmartphone,
  pulse: Activity,
  radar: Radar,
  rotate: RotateCcw,
  scale: Scale,
  scan: ScanSearch,
  search: Search,
  shield: ShieldCheck,
  siren: Siren,
  spark: Sparkles,
  swords: Swords,
  terminal: Terminal,
  users: Users,
  workflow: Workflow,
  wrench: Wrench,
};

export function Icon({ name, size = 22, strokeWidth = 1.7, ...props }) {
  const Cmp = map[name] || ShieldCheck;
  return <Cmp size={size} strokeWidth={strokeWidth} {...props} />;
}
