import {
  Activity,
  ArchiveRestore,
  BadgeCheck,
  BookMarked,
  BookOpen,
  Boxes,
  Brain,
  BrickWall,
  Bug,
  Building2,
  CalendarClock,
  ChartNoAxesColumn,
  CircleCheck,
  CircleGauge,
  ClipboardCheck,
  Clock,
  Cloud,
  CloudCog,
  Code,
  Compass,
  Container,
  Cpu,
  CreditCard,
  Crosshair,
  Crown,
  Database,
  Eye,
  Factory,
  FileBadge,
  FileCheck,
  FileCode,
  FileText,
  Fingerprint,
  FolderOpen,
  FolderGit2,
  Funnel,
  Gauge,
  Gavel,
  Ghost,
  GitBranch,
  Globe,
  GlobeLock,
  GraduationCap,
  Handshake,
  HardDrive,
  HeartPulse,
  Hexagon,
  Hospital,
  IdCard,
  KeyRound,
  Landmark,
  Layers,
  ListChecks,
  ListTodo,
  Lock,
  MailWarning,
  Map,
  MapPinned,
  MessagesSquare,
  MonitorSmartphone,
  Network,
  Notebook,
  Plug,
  Presentation,
  Radar,
  Repeat,
  RotateCcw,
  Route,
  Scale,
  ScanSearch,
  ScrollText,
  Search,
  Server,
  Share2,
  ShieldAlert,
  ShieldCheck,
  ShieldPlus,
  ShoppingBag,
  Siren,
  Sparkles,
  Split,
  Stethoscope,
  Swords,
  Tags,
  Target,
  Terminal,
  Ticket,
  Timer,
  Truck,
  Unplug,
  UserCheck,
  UserRoundSearch,
  Users,
  UsersRound,
  Waypoints,
  Workflow,
  Wrench,
} from "lucide-react";

const map = {
  activity: Activity,
  "archive-restore": ArchiveRestore,
  badge: BadgeCheck,
  book: BookOpen,
  "book-mark": BookMarked,
  boxes: Boxes,
  brain: Brain,
  brick: BrickWall,
  bug: Bug,
  building: Building2,
  "calendar-clock": CalendarClock,
  cart: ShoppingBag,
  chart: ChartNoAxesColumn,
  "circle-check": CircleCheck,
  clipboard: ClipboardCheck,
  clock: Clock,
  cloud: Cloud,
  "cloud-cog": CloudCog,
  code: Code,
  compass: Compass,
  container: Container,
  cpu: Cpu,
  "credit-card": CreditCard,
  crosshair: Crosshair,
  crown: Crown,
  database: Database,
  eye: Eye,
  factory: Factory,
  file: FileText,
  "file-badge": FileBadge,
  "file-check": FileCheck,
  "file-code": FileCode,
  fingerprint: Fingerprint,
  folder: FolderOpen,
  funnel: Funnel,
  gauge: Gauge,
  "gauge-circle": CircleGauge,
  gavel: Gavel,
  ghost: Ghost,
  git: FolderGit2,
  "git-branch": GitBranch,
  globe: Globe,
  "globe-lock": GlobeLock,
  "grad-cap": GraduationCap,
  handshake: Handshake,
  "hard-drive": HardDrive,
  heart: HeartPulse,
  hexagon: Hexagon,
  hospital: Hospital,
  "id-card": IdCard,
  key: KeyRound,
  landmark: Landmark,
  layers: Layers,
  "list-checks": ListChecks,
  "list-todo": ListTodo,
  lock: Lock,
  "mail-warning": MailWarning,
  map: Map,
  pin: MapPinned,
  messages: MessagesSquare,
  monitor: MonitorSmartphone,
  network: Network,
  notebook: Notebook,
  plug: Plug,
  presentation: Presentation,
  pulse: Activity,
  radar: Radar,
  repeat: Repeat,
  rotate: RotateCcw,
  route: Route,
  scale: Scale,
  scan: ScanSearch,
  scroll: ScrollText,
  search: Search,
  server: Server,
  share: Share2,
  "shield-alert": ShieldAlert,
  shield: ShieldCheck,
  "shield-plus": ShieldPlus,
  siren: Siren,
  spark: Sparkles,
  split: Split,
  stethoscope: Stethoscope,
  swords: Swords,
  tags: Tags,
  target: Target,
  terminal: Terminal,
  ticket: Ticket,
  timer: Timer,
  truck: Truck,
  unplug: Unplug,
  "user-check": UserCheck,
  "user-search": UserRoundSearch,
  users: Users,
  "users-round": UsersRound,
  waypoints: Waypoints,
  workflow: Workflow,
  wrench: Wrench,
};

export function Icon({ name, size = 22, strokeWidth = 1.75, className, ...props }) {
  const Cmp = map[name] || ShieldCheck;
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} {...props} />;
}
